### ISSUE TITLE
Not following the license from upstream

### ISSUE THREAD

**Issue by axtloss** [Pear-Project/piri-backend#2]
This fork is not following the license from my [original project](https://github.com/axtloss/vAssistant), I already tried to contact you with two emails, which you just ignored.
You should either add the license from upstream and follow it's terms of remove this repository and stop using piri.

attached are the two emails i already sent you

![Screenshot from 2021-11-15 20-51-42](https://user-images.githubusercontent.com/60044824/141845045-fa3676b7-3d5a-41df-932e-a21f33e42c93.png)
![Screenshot from 2021-11-15 20-51-29](https://user-images.githubusercontent.com/60044824/141845050-09669448-b57e-4555-8c27-b5815b306eb1.png)

**Comment by alxb421** [comment]
Thank you for contacting, I currently face some mail problems and I couldn't receive your emails. The problem will be fixed anytime soon, and as for the neofetch thing, it created confusion, when users asked if you are a co-developer or something. 

For the Piri backed, you changed the license right after our "discussion", ![Screenshot_20211115-221046_Chrome](https://user-images.githubusercontent.com/72302254/141847726-bdb5a92c-9d7e-43d6-a99a-721d2d5cf28c.jpg)  meaning that the fork was done when the license was still GPL v3. I will rewrite the py code to satisfy you and your strange pleasures with licenses.

Happy to har from you, 
Alex.

**Comment by axtloss** [comment]
You were already violating the license since the 16th March, when you ["nuked" your repo](https://github.com/Pear-Project/piri-backend/commit/1a31c2e87fe7687f9299132cf559b050226d1493) to start again, at that time vAssistant was still on GPL v3, I'd expect you to have at least added back that license.
Then also, my "strange pleasures with licenses" is just me wanting to be credited for my work, I have added a license to my project and according to that license, forks will have to include it too, both with the GPL v3 and the nolicense, It's fully in my right to make forks follow the terms of that license.
As a distro maintainer I'd expect you to be more serious with stuff like this.
However I'm happy that you're going to comply with the license.
Thanks for the quick response

**Comment by alxb421** [comment]
> You were already violating the license since the 16th March, when you ["nuked" your repo](https://github.com/Pear-Project/piri-backend/commit/1a31c2e87fe7687f9299132cf559b050226d1493) to start again, at that time vAssistant was still on GPL v3, I'd expect you to have at least added back that license. Then also, my "strange pleasures with licenses" is just me wanting to be credited for my work, I have added a license to my project and according to that license, forks will have to include it too, both with the GPL v3 and the nolicense, It's fully in my right to make forks follow the terms of that license. As a distro maintainer I'd expect you to be more serious with stuff like this. However I'm happy that you're going to comply with the license. Thanks for the quick response

![Screenshot_20211115-231225_Chrome](https://user-images.githubusercontent.com/72302254/141854580-2572ca23-805e-43a0-a3a8-f2dcfae6fff4.jpg)
Credits already gave in the README file. Thread closed

**Comment by axtloss** [comment]
Just crediting me is  not enough to satisfy the nolicense, you still need to add the license itself to the project, as stated in the first term (any redistributions in either source code or binary form must retain this copyright notice in its entirety), there also needs to be an easy way to access the original source from me in piri itself, as stated in the second term (any and all redistributions must credit the original author of the source code, and provide an easily accessible way to find the original author's source code, wherever it may be published)

**Comment by axtloss** [comment]
This is now 4 days old and you still have not adjusted the project to follow the terms of the license, are you ever going to comply with any licenses or are they irrelevant to you?  This is just another example of why I left pearos, youre just being ignorant, except this time it's publicly visible.

**Comment by alxb421** [comment]
> This is now 4 days old and you still have not adjusted the project to follow the terms of the license, are you ever going to comply with any licenses or are they irrelevant to you? This is just another example of why I left pearos, youre just being ignorant, except this time it's publicly visible.

I am in progress of rewriting the python script. This is why you never understood me: you didn't gave me enough time to finish my work

**Comment by axtloss** [comment]
rewriting the python script is fine and all, but this is still a fork, meaning you still have to follow the terms of the license while you use my code

**Comment by axtloss** [comment]
almost 19 days, no changes, how hard is it to just add the license to the repo????
